import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import QRCode from 'qrcode';
import {Pool} from 'pg';
import {z} from 'zod';

const app=express();
const port=Number(process.env.PORT||5000);
const production=process.env.NODE_ENV==='production';
if(!process.env.DATABASE_URL) throw new Error('DATABASE_URL is required');
if(!process.env.JWT_SECRET || process.env.JWT_SECRET.length<32) throw new Error('JWT_SECRET must be at least 32 characters');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:production?{rejectUnauthorized:false}:undefined,max:10,connectionTimeoutMillis:10000,idleTimeoutMillis:30000});
app.disable('x-powered-by');
app.use(helmet());
app.use(cors({origin:process.env.CORS_ORIGIN?process.env.CORS_ORIGIN.split(',').map(v=>v.trim()):true,credentials:true}));
app.use(express.json({limit:'2mb'}));
app.use(rateLimit({windowMs:15*60*1000,limit:300,standardHeaders:'draft-8',legacyHeaders:false}));
const authLimit=rateLimit({windowMs:15*60*1000,limit:25,standardHeaders:'draft-8',legacyHeaders:false});
const asyncRoute=fn=>(req,res,next)=>Promise.resolve(fn(req,res,next)).catch(next);
const roles=['CEO','ADMIN','PARTNER','INSTRUCTOR','STUDENT'];
function tokenFor(id){return jwt.sign({sub:id,type:'access'},process.env.JWT_SECRET,{expiresIn:process.env.JWT_EXPIRES_IN||'7d'});}
async function getUser(id){const {rows}=await pool.query(`SELECT u.id,u.email,u.full_name,u.status,u.theme_preference,COALESCE(array_agg(DISTINCT r.code) FILTER(WHERE r.code IS NOT NULL),'{}') roles,COALESCE(MIN(r.code),'STUDENT') primary_role FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id WHERE u.id=$1 GROUP BY u.id`,[id]);return rows[0]||null;}
const auth=asyncRoute(async(req,res,next)=>{const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({success:false,error:'Authentication required.'});try{const p=jwt.verify(h.slice(7),process.env.JWT_SECRET);const u=await getUser(p.sub);if(!u||u.status!=='active')return res.status(401).json({success:false,error:'Invalid session.'});req.user=u;next();}catch{return res.status(401).json({success:false,error:'Invalid or expired session.'});}});
const role=(...allowed)=>(req,res,next)=>allowed.some(r=>req.user?.roles?.includes(r))?next():res.status(403).json({success:false,error:'Forbidden.'});
async function audit(req,action,type,id,metadata={}){await pool.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id,metadata,ip_address,user_agent) VALUES($1,$2,$3,$4,$5,$6,$7)`,[req.user?.id||null,action,type,id,JSON.stringify(metadata),req.ip,req.get('user-agent')||null]);}
async function partnerByCode(code){if(!code)return null;const {rows}=await pool.query(`SELECT id,user_id,referral_code FROM partners WHERE referral_code=$1 AND status='active' LIMIT 1`,[code]);return rows[0]||null;}
async function recalcLevel(client,userId){const points=(await client.query(`SELECT COALESCE(SUM(points_delta),0)::int points FROM point_ledger WHERE user_id=$1 AND status='valid'`,[userId])).rows[0].points;const refs=(await client.query(`SELECT COUNT(*)::int n FROM referrals WHERE referred_user_id=$1 AND status='valid'`,[userId])).rows[0].n;const mastery=(await client.query(`SELECT COUNT(*)::int n FROM skill_mastery WHERE user_id=$1 AND status='verified'`,[userId])).rows[0].n;const levels=(await client.query(`SELECT level_number,points_required FROM levels ORDER BY level_number DESC`)).rows;let level=1;for(const l of levels){if(points>=Number(l.points_required)){level=Number(l.level_number);break;}}await client.query(`INSERT INTO user_levels(user_id,current_level,points,valid_referrals,verified_mastery_count) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_id) DO UPDATE SET current_level=EXCLUDED.current_level,points=EXCLUDED.points,valid_referrals=EXCLUDED.valid_referrals,verified_mastery_count=EXCLUDED.verified_mastery_count,updated_at=now()`,[userId,level,points,refs,mastery]);return{points:Number(points),level,refs:Number(refs),mastery:Number(mastery)};}
async function verifyOrder(client,orderId,reviewerId,req){const order=(await client.query(`SELECT o.*,p.name package_name,p.access_duration_days FROM orders o LEFT JOIN packages p ON p.id=o.package_id WHERE o.id=$1 FOR UPDATE`,[orderId])).rows[0];if(!order)throw Object.assign(new Error('Order not found'),{statusCode:404});if(order.status==='paid')return order;await client.query(`UPDATE orders SET status='paid',updated_at=now() WHERE id=$1`,[orderId]);await client.query(`INSERT INTO payments(order_id,provider,amount_inr,status,verified_at,verified_by) VALUES($1,'manual',$2,'verified',now(),$3) ON CONFLICT(order_id) DO UPDATE SET status='verified',verified_at=now(),verified_by=$3`,[orderId,order.total_inr,reviewerId]);
if(order.package_id){await client.query(`INSERT INTO enrollments(user_id,package_id,order_id,access_expires_at) VALUES($1,$2,$3,CASE WHEN $4 IS NULL THEN NULL ELSE now()+($4*interval '1 day') END) ON CONFLICT DO NOTHING`,[order.user_id,order.package_id,order.id,order.access_duration_days]);const cs=(await client.query(`SELECT course_id FROM package_courses WHERE package_id=$1`,[order.package_id])).rows;for(const c of cs.rows)await client.query(`INSERT INTO enrollments(user_id,course_id,order_id) VALUES($1,$2,$3) ON CONFLICT DO NOTHING`,[order.user_id,c.course_id,order.id]);}
const partner=await partnerByCode(order.referral_code);if(partner){const rule=(await client.query(`SELECT * FROM commission_rules WHERE active=true AND (package_id=$1 OR package_id IS NULL) AND effective_from<=now() AND (effective_to IS NULL OR effective_to>now()) ORDER BY (package_id IS NOT NULL) DESC,effective_from DESC LIMIT 1`,[order.package_id])).rows[0];if(rule){const amount=rule.commission_type==='percent'?Number(order.total_inr)*Number(rule.value)/100:Number(rule.value);if(amount>0){const c=(await client.query(`INSERT INTO commissions(partner_id,order_id,rule_id,amount_inr,status) VALUES($1,$2,$3,$4,'available') ON CONFLICT(partner_id,order_id) DO NOTHING RETURNING id,amount_inr`,[partner.id,order.id,rule.id,amount])).rows[0];if(c)await client.query(`INSERT INTO earnings_ledger(partner_id,commission_id,amount_inr,status,description) VALUES($1,$2,$3,'available',$4)`,[partner.id,c.id,amount,`Commission for order ${order.id}`]);}}await client.query(`UPDATE referrals SET status='valid',converted_order_id=$1,converted_at=now() WHERE partner_id=$2 AND referred_user_id=$3`,[order.id,partner.id,order.user_id]);}
await client.query(`INSERT INTO point_ledger(user_id,source_type,source_id,points_delta,status,description) VALUES($1,'verified_order',$2,GREATEST(1,FLOOR($3/100))::int,'valid','Verified package purchase') ON CONFLICT(source_type,source_id,user_id) DO NOTHING`,[order.user_id,order.id,Number(order.total_inr)]);await recalcLevel(client,order.user_id);await audit(req,'payment.verified','order',order.id,{total:Number(order.total_inr)});return order;}

app.get('/health',(_req,res)=>res.json({success:true,status:'healthy',timestamp:new Date().toISOString()}));
app.get('/api/health',asyncRoute(async(_req,res)=>{const r=await pool.query('SELECT now() t');res.json({success:true,api:'healthy',database:'connected',time:r.rows[0].t})}));
app.get('/',(_req,res)=>res.json({success:true,name:'Skill Commerce Platform API',version:'1.0.0'}));

app.post('/api/auth/signup',authLimit,asyncRoute(async(req,res)=>{const v=z.object({fullName:z.string().trim().min(2).max(100),email:z.string().trim().email(),password:z.string().min(8).max(128),referralCode:z.string().trim().max(64).optional().nullable()}).parse(req.body);const exists=(await pool.query('SELECT id FROM users WHERE lower(email)=lower($1)',[v.email])).rows[0];if(exists)return res.status(409).json({success:false,error:'Email already registered.'});const c=await pool.connect();try{await c.query('BEGIN');const u=(await c.query(`INSERT INTO users(email,full_name,password_hash) VALUES(lower($1),$2,$3) RETURNING id,email,full_name,status`,[v.email,v.fullName,await bcrypt.hash(v.password,12)])).rows[0];const roleId=(await c.query(`SELECT id FROM roles WHERE code='STUDENT'`)).rows[0]?.id;if(!roleId)throw new Error('Database seed missing STUDENT role.');await c.query('INSERT INTO user_roles(user_id,role_id) VALUES($1,$2)',[u.id,roleId]);const p=await partnerByCode(v.referralCode);if(p)await c.query(`INSERT INTO referrals(partner_id,referred_user_id,source,status) VALUES($1,$2,'signup','pending') ON CONFLICT DO NOTHING`,[p.id,u.id]);await c.query(`INSERT INTO audit_logs(actor_user_id,action,entity_type,entity_id) VALUES($1,'signup','user',$1)`,[u.id]);await c.query('COMMIT');const fresh=await getUser(u.id);res.status(201).json({success:true,token:tokenFor(fresh.id),user:fresh});}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
app.post('/api/auth/login',authLimit,asyncRoute(async(req,res)=>{const v=z.object({email:z.string().trim().email(),password:z.string().min(1).max(128)}).parse(req.body);const u=(await pool.query(`SELECT * FROM users WHERE lower(email)=lower($1) LIMIT 1`,[v.email])).rows[0];if(!u||u.status!=='active'||!(await bcrypt.compare(v.password,u.password_hash)))return res.status(401).json({success:false,error:'Invalid email or password.'});const fresh=await getUser(u.id);await audit({...req,user:fresh},'login','user',fresh.id);res.json({success:true,token:tokenFor(fresh.id),user:fresh})}));
app.get('/api/auth/me',auth,(req,res)=>res.json({success:true,user:req.user}));

app.get('/api/catalog',asyncRoute(async(_req,res)=>{const [p,c,m,w]=await Promise.all([pool.query(`SELECT * FROM packages WHERE active=true ORDER BY display_order`),pool.query(`SELECT c.id,c.title,c.slug,c.description,c.price_inr,c.thumbnail_url,cat.name category,u.full_name instructor_name FROM courses c LEFT JOIN categories cat ON cat.id=c.category_id LEFT JOIN instructors i ON i.id=c.instructor_id LEFT JOIN users u ON u.id=i.user_id WHERE c.status='published' ORDER BY c.created_at DESC`),pool.query(`SELECT m.id,m.title,m.description,m.thumbnail_url,m.price_inr,m.mode,m.schedule_at,m.seats,u.full_name instructor_name FROM masterclasses m LEFT JOIN instructors i ON i.id=m.instructor_id LEFT JOIN users u ON u.id=i.user_id WHERE m.status='published' ORDER BY m.schedule_at NULLS LAST`),pool.query(`SELECT w.id,w.title,w.description,w.price_inr,w.schedule_at,w.seats,u.full_name instructor_name FROM workshops w LEFT JOIN instructors i ON i.id=w.instructor_id LEFT JOIN users u ON u.id=i.user_id WHERE w.status='published' ORDER BY w.schedule_at NULLS LAST`)]);res.json({success:true,packages:p.rows,courses:c.rows,masterclasses:m.rows,workshops:w.rows})}));
app.post('/api/orders/package',auth,asyncRoute(async(req,res)=>{const v=z.object({packageId:z.string().uuid(),referralCode:z.string().trim().max(64).optional().nullable(),couponCode:z.string().trim().max(64).optional().nullable()}).parse(req.body);const p=(await pool.query('SELECT * FROM packages WHERE id=$1 AND active=true',[v.packageId])).rows[0];if(!p)return res.status(404).json({success:false,error:'Package not found.'});let total=Number(p.price_inr),discount=0;if(v.couponCode){const c=(await pool.query(`SELECT * FROM coupons WHERE code=$1 AND active=true AND (valid_from IS NULL OR valid_from<=now()) AND (valid_until IS NULL OR valid_until>now())`,[v.couponCode])).rows[0];if(c){discount=c.discount_type==='percent'?Math.min(total,total*Number(c.value)/100):Math.min(total,Number(c.value));total-=discount;}}const partner=await partnerByCode(v.referralCode);const o=(await pool.query(`INSERT INTO orders(user_id,order_type,package_id,subtotal_inr,discount_inr,total_inr,coupon_code,referral_code,status) VALUES($1,'package',$2,$3,$4,$5,$6,$7,'pending') RETURNING id,total_inr,status,created_at`,[req.user.id,p.id,Number(p.price_inr),discount,total,v.couponCode||null,partner?.referral_code||null])).rows[0];await audit(req,'order.created','order',o.id,{packageId:p.id,total});res.status(201).json({success:true,order:o,payment_method:'manual_reference'})}));
app.post('/api/orders/:id/payment-reference',auth,asyncRoute(async(req,res)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const {reference}=z.object({reference:z.string().trim().min(3).max(200)}).parse(req.body);const o=(await pool.query('SELECT * FROM orders WHERE id=$1 AND user_id=$2',[id,req.user.id])).rows[0];if(!o)return res.status(404).json({success:false,error:'Order not found.'});if(o.status!=='pending')return res.status(409).json({success:false,error:'Order is not pending.'});await pool.query(`INSERT INTO payments(order_id,provider,provider_payment_id,amount_inr,status) VALUES($1,'manual',$2,$3,'pending') ON CONFLICT(order_id) DO UPDATE SET provider_payment_id=EXCLUDED.provider_payment_id,status='pending'`,[id,reference,o.total_inr]);await audit(req,'payment.reference_submitted','order',id);res.json({success:true,message:'Payment reference submitted for review.'})}));
app.get('/api/me/orders',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT o.id,o.total_inr,o.status,o.created_at,p.name package_name,pay.provider_payment_id,pay.status payment_status FROM orders o LEFT JOIN packages p ON p.id=o.package_id LEFT JOIN payments pay ON pay.order_id=o.id WHERE o.user_id=$1 ORDER BY o.created_at DESC`,[req.user.id]);res.json({success:true,orders:rows})}));
app.get('/api/me/enrollments',auth,asyncRoute(async(req,res)=>{const {rows}=await pool.query(`SELECT e.id,e.progress_percent,e.access_expires_at,c.id course_id,c.title course_title,p.name package_name FROM enrollments e LEFT JOIN courses c ON c.id=e.course_id LEFT JOIN packages p ON p.id=e.package_id WHERE e.user_id=$1 ORDER BY e.created_at DESC`,[req.user.id]);res.json({success:true,enrollments:rows})}));
app.patch('/api/me/enrollments/:id/progress',auth,asyncRoute(async(req,res)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const {progress}=z.object({progress:z.coerce.number().min(0).max(100)}).parse(req.body);const r=(await pool.query('UPDATE enrollments SET progress_percent=$1 WHERE id=$2 AND user_id=$3 RETURNING id,progress_percent',[progress,id,req.user.id])).rows[0];if(!r)return res.status(404).json({success:false,error:'Enrollment not found.'});res.json({success:true,enrollment:r})}));
app.get('/api/me/level',auth,asyncRoute(async(req,res)=>{const level=(await pool.query(`SELECT ul.current_level,ul.points,ul.valid_referrals,ul.verified_mastery_count FROM user_levels ul WHERE ul.user_id=$1`,[req.user.id])).rows[0]||{current_level:1,points:0,valid_referrals:0,verified_mastery_count:0};const rewards=(await pool.query(`SELECT r.id,r.name,r.description,r.level_number,rc.status claim_status FROM rewards r LEFT JOIN reward_claims rc ON rc.reward_id=r.id AND rc.user_id=$1 WHERE r.active=true ORDER BY r.level_number`,[req.user.id])).rows;res.json({success:true,level,rewards})}));
app.post('/api/rewards/:id/claim',auth,asyncRoute(async(req,res)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const r=(await pool.query('SELECT * FROM rewards WHERE id=$1 AND active=true',[id])).rows[0];if(!r)return res.status(404).json({success:false,error:'Reward not found.'});const l=(await pool.query('SELECT current_level FROM user_levels WHERE user_id=$1',[req.user.id])).rows[0];if(Number(l?.current_level||1)<Number(r.level_number))return res.status(403).json({success:false,error:'Reward not yet eligible.'});const claim=(await pool.query(`INSERT INTO reward_claims(reward_id,user_id,eligibility_snapshot,status) VALUES($1,$2,$3,'pending') ON CONFLICT(reward_id,user_id) DO NOTHING RETURNING id,status`,[id,req.user.id,JSON.stringify({currentLevel:Number(l.current_level)})])).rows[0];if(!claim)return res.status(409).json({success:false,error:'Reward already claimed.'});res.status(201).json({success:true,claim})}));

app.get('/api/partner/me',auth,role('PARTNER'),asyncRoute(async(req,res)=>{const p=(await pool.query('SELECT * FROM partners WHERE user_id=$1',[req.user.id])).rows[0];if(!p)return res.status(404).json({success:false,error:'Partner profile not found.'});const s=(await pool.query(`SELECT COALESCE(SUM(CASE WHEN status='available' THEN amount_inr ELSE 0 END),0) available,COALESCE(SUM(CASE WHEN status='withdrawn' THEN amount_inr ELSE 0 END),0) withdrawn,COALESCE(SUM(CASE WHEN status='pending' THEN amount_inr ELSE 0 END),0) pending FROM earnings_ledger WHERE partner_id=$1`,[p.id])).rows[0];const r=(await pool.query(`SELECT COUNT(*)::int total,COUNT(*) FILTER(WHERE status='valid')::int valid FROM referrals WHERE partner_id=$1`,[p.id])).rows[0];const ledger=(await pool.query(`SELECT id,amount_inr,status,description,created_at FROM earnings_ledger WHERE partner_id=$1 ORDER BY created_at DESC LIMIT 100`,[p.id])).rows;const withdrawals=(await pool.query(`SELECT id,amount_inr,status,rejection_reason,created_at,reviewed_at FROM withdrawals WHERE partner_id=$1 ORDER BY created_at DESC LIMIT 100`,[p.id])).rows;res.json({success:true,partner:p,summary:s,referrals:r,ledger,withdrawals,referralUrl:`${process.env.CORS_ORIGIN||''}/?ref=${encodeURIComponent(p.referral_code)}`})}));
app.get('/api/partner/qr.svg',auth,role('PARTNER'),asyncRoute(async(req,res)=>{const p=(await pool.query('SELECT referral_code FROM partners WHERE user_id=$1 AND status=\'active\'', [req.user.id])).rows[0];if(!p)return res.status(404).send('Partner profile not found');const url=`${process.env.CORS_ORIGIN||'https://example.invalid'}/?ref=${encodeURIComponent(p.referral_code)}`;res.type('image/svg+xml').send(await QRCode.toString(url,{type:'svg',width:320,margin:2}))}));
app.post('/api/partner/withdrawals',auth,role('PARTNER'),asyncRoute(async(req,res)=>{const {amountInr}=z.object({amountInr:z.coerce.number().min(100).max(10000000)}).parse(req.body);const p=(await pool.query('SELECT * FROM partners WHERE user_id=$1 AND status=\'active\'',[req.user.id])).rows[0];if(!p)return res.status(404).json({success:false,error:'Partner profile not found.'});const a=Number((await pool.query(`SELECT COALESCE(SUM(CASE WHEN status='available' THEN amount_inr ELSE 0 END),0) a FROM earnings_ledger WHERE partner_id=$1`,[p.id])).rows[0].a);if(amountInr> a)return res.status(400).json({success:false,error:'Insufficient available balance.'});const w=(await pool.query(`INSERT INTO withdrawals(partner_id,amount_inr,status) VALUES($1,$2,'pending') RETURNING id,amount_inr,status,created_at`,[p.id,amountInr])).rows[0];await audit(req,'withdrawal.requested','withdrawal',w.id,{amountInr});res.status(201).json({success:true,withdrawal:w})}));

app.get('/api/ceo/overview',auth,role('CEO'),asyncRoute(async(_req,res)=>{const q=async sql=>(await pool.query(sql)).rows[0];res.json({success:true,stats:{users:Number((await q('SELECT count(*) n FROM users')).n),courses:Number((await q("SELECT count(*) n FROM courses WHERE status='published'")).n),pendingOrders:Number((await q("SELECT count(*) n FROM orders WHERE status='pending'")).n),pendingWithdrawals:Number((await q("SELECT count(*) n FROM withdrawals WHERE status='pending'")).n),revenue:Number((await q("SELECT coalesce(sum(total_inr),0) n FROM orders WHERE status='paid'")).n)}})}));
app.get('/api/ceo/users',auth,role('CEO'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT u.id,u.full_name,u.email,u.status,u.created_at,COALESCE(array_agg(DISTINCT r.code) FILTER(WHERE r.code IS NOT NULL),'{}') roles FROM users u LEFT JOIN user_roles ur ON ur.user_id=u.id LEFT JOIN roles r ON r.id=ur.role_id GROUP BY u.id ORDER BY u.created_at DESC LIMIT 500`);res.json({success:true,users:rows})}));
app.get('/api/ceo/payment-review',auth,role('CEO'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT o.id,o.total_inr,o.created_at,u.full_name,u.email,p.name package_name,pay.provider_payment_id FROM orders o JOIN users u ON u.id=o.user_id LEFT JOIN packages p ON p.id=o.package_id LEFT JOIN payments pay ON pay.order_id=o.id WHERE o.status='pending' ORDER BY o.created_at`);res.json({success:true,orders:rows})}));
app.post('/api/ceo/orders/:id/verify',auth,role('CEO'),asyncRoute(async(req,res)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const c=await pool.connect();try{await c.query('BEGIN');const o=await verifyOrder(c,id,req.user.id,req);await c.query('COMMIT');res.json({success:true,message:'Payment verified, enrollment and eligible commission/points processed.',order:o})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
app.patch('/api/ceo/packages/:id',auth,role('CEO'),asyncRoute(async(req,res)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const {priceInr,active}=z.object({priceInr:z.coerce.number().min(0),active:z.boolean().optional()}).parse(req.body);const p=(await pool.query(`UPDATE packages SET price_inr=$1,active=COALESCE($2,active),updated_at=now() WHERE id=$3 RETURNING *`,[priceInr,active??null,id])).rows[0];if(!p)return res.status(404).json({success:false,error:'Package not found.'});await audit(req,'package.updated','package',id,{priceInr});res.json({success:true,package:p})}));
app.get('/api/ceo/withdrawals',auth,role('CEO'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT w.id,w.amount_inr,w.status,w.created_at,u.full_name,u.email,p.referral_code FROM withdrawals w JOIN partners p ON p.id=w.partner_id JOIN users u ON u.id=p.user_id WHERE w.status='pending' ORDER BY w.created_at`);res.json({success:true,withdrawals:rows})}));
app.post('/api/ceo/withdrawals/:id/review',auth,role('CEO'),asyncRoute(async(req,res)=>{const {id}=z.object({id:z.string().uuid()}).parse(req.params);const v=z.object({decision:z.enum(['approved','rejected']),rejectionReason:z.string().max(500).optional().nullable()}).parse(req.body);const c=await pool.connect();try{await c.query('BEGIN');const w=(await c.query(`SELECT * FROM withdrawals WHERE id=$1 FOR UPDATE`,[id])).rows[0];if(!w){await c.query('ROLLBACK');return res.status(404).json({success:false,error:'Withdrawal not found.'});}if(w.status!=='pending'){await c.query('ROLLBACK');return res.status(409).json({success:false,error:'Already reviewed.'});}if(v.decision==='approved'){const bal=Number((await c.query(`SELECT coalesce(sum(case when status='available' then amount_inr else 0 end),0) a FROM earnings_ledger WHERE partner_id=$1`,[w.partner_id])).rows[0].a);if(Number(w.amount_inr)>bal){await c.query('ROLLBACK');return res.status(409).json({success:false,error:'Balance no longer sufficient.'});}await c.query(`INSERT INTO earnings_ledger(partner_id,amount_inr,status,description) VALUES($1,$2,'withdrawn',$3)`,[w.partner_id,-Number(w.amount_inr),`Withdrawal ${w.id}`]);await c.query(`UPDATE withdrawals SET status='approved',reviewed_by=$1,reviewed_at=now() WHERE id=$2`,[req.user.id,id]);}else await c.query(`UPDATE withdrawals SET status='rejected',reviewed_by=$1,reviewed_at=now(),rejection_reason=$2 WHERE id=$3`,[req.user.id,v.rejectionReason||null,id]);await c.query('COMMIT');await audit(req,`withdrawal.${v.decision}`,'withdrawal',id);res.json({success:true})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}));
app.get('/api/ceo/commission-rules',auth,role('CEO'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT cr.id,cr.package_id,cr.commission_type,cr.value,cr.active,p.name package_name FROM commission_rules cr LEFT JOIN packages p ON p.id=cr.package_id ORDER BY cr.effective_from DESC`);res.json({success:true,rules:rows})}));
app.post('/api/ceo/commission-rules',auth,role('CEO'),asyncRoute(async(req,res)=>{const v=z.object({packageId:z.string().uuid().optional().nullable(),commissionType:z.enum(['fixed','percent']),value:z.coerce.number().min(0)}).parse(req.body);const r=(await pool.query(`INSERT INTO commission_rules(package_id,commission_type,value,active) VALUES($1,$2,$3,true) RETURNING *`,[v.packageId||null,v.commissionType,v.value])).rows[0];await audit(req,'commission_rule.created','commission_rule',r.id,v);res.status(201).json({success:true,rule:r})}));
app.get('/api/ceo/audit',auth,role('CEO'),asyncRoute(async(_req,res)=>{const {rows}=await pool.query(`SELECT al.id,al.action,al.entity_type,al.entity_id,al.created_at,u.email actor_email FROM audit_logs al LEFT JOIN users u ON u.id=al.actor_user_id ORDER BY al.created_at DESC LIMIT 500`);res.json({success:true,logs:rows})}));

app.post('/api/instructor/courses',auth,role('INSTRUCTOR'),asyncRoute(async(req,res)=>{const v=z.object({title:z.string().min(2).max(150),description:z.string().max(10000).optional().nullable(),priceInr:z.coerce.number().min(0),categoryId:z.string().uuid().optional().nullable()}).parse(req.body);const i=(await pool.query('SELECT id FROM instructors WHERE user_id=$1',[req.user.id])).rows[0];if(!i)return res.status(404).json({success:false,error:'Instructor profile not found.'});const slug=v.title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')+'-'+Date.now();const c=(await pool.query(`INSERT INTO courses(instructor_id,category_id,title,slug,description,price_inr,status) VALUES($1,$2,$3,$4,$5,$6,'draft') RETURNING *`,[i.id,v.categoryId||null,v.title,slug,v.description||null,v.priceInr])).rows[0];res.status(201).json({success:true,course:c})}));
app.get('/api/instructor/content',auth,role('INSTRUCTOR'),asyncRoute(async(req,res)=>{const i=(await pool.query('SELECT id FROM instructors WHERE user_id=$1',[req.user.id])).rows[0];if(!i)return res.status(404).json({success:false,error:'Instructor profile not found.'});const [c,m,w]=await Promise.all([pool.query('SELECT * FROM courses WHERE instructor_id=$1 ORDER BY created_at DESC',[i.id]),pool.query('SELECT * FROM masterclasses WHERE instructor_id=$1 ORDER BY created_at DESC',[i.id]),pool.query('SELECT * FROM workshops WHERE instructor_id=$1 ORDER BY created_at DESC',[i.id])]);res.json({success:true,courses:c.rows,masterclasses:m.rows,workshops:w.rows})}));
app.post('/api/registrations/masterclass',auth,asyncRoute(async(req,res)=>{const {masterclassId}=z.object({masterclassId:z.string().uuid()}).parse(req.body);const m=(await pool.query(`SELECT id,price_inr,seats,(SELECT count(*) FROM registrations r WHERE r.masterclass_id=m.id AND r.status='registered') registered FROM masterclasses m WHERE id=$1 AND status='published'`,[masterclassId])).rows[0];if(!m)return res.status(404).json({success:false,error:'Masterclass not found.'});if(m.seats&&Number(m.registered)>=Number(m.seats))return res.status(409).json({success:false,error:'No seats remaining.'});const r=(await pool.query(`INSERT INTO registrations(user_id,masterclass_id,status) VALUES($1,$2,'registered') ON CONFLICT DO NOTHING RETURNING *`,[req.user.id,masterclassId])).rows[0];if(!r)return res.status(409).json({success:false,error:'Already registered.'});res.status(201).json({success:true,registration:r,priceInr:Number(m.price_inr)})}));
app.post('/api/registrations/workshop',auth,asyncRoute(async(req,res)=>{const {workshopId}=z.object({workshopId:z.string().uuid()}).parse(req.body);const w=(await pool.query(`SELECT id,price_inr,seats,(SELECT count(*) FROM registrations r WHERE r.workshop_id=w.id AND r.status='registered') registered FROM workshops w WHERE id=$1 AND status='published'`,[workshopId])).rows[0];if(!w)return res.status(404).json({success:false,error:'Workshop not found.'});if(w.seats&&Number(w.registered)>=Number(w.seats))return res.status(409).json({success:false,error:'No seats remaining.'});const r=(await pool.query(`INSERT INTO registrations(user_id,workshop_id,status) VALUES($1,$2,'registered') ON CONFLICT DO NOTHING RETURNING *`,[req.user.id,workshopId])).rows[0];if(!r)return res.status(409).json({success:false,error:'Already registered.'});res.status(201).json({success:true,registration:r,priceInr:Number(w.price_inr)})}));

app.use((err,_req,res,_next)=>{console.error(err);if(err instanceof z.ZodError)return res.status(400).json({success:false,error:'Validation failed.',details:err.issues});res.status(err.statusCode||500).json({success:false,error:production?'Internal server error':err.message})});
process.on('SIGTERM',async()=>{await pool.end();process.exit(0)});process.on('SIGINT',async()=>{await pool.end();process.exit(0)});
app.listen(port,()=>console.log(`Skill Commerce backend listening on ${port}`));
